---
- hosts: "{{HOST}}"
  connection: local

  roles:
    - role: deployHazelcast
      when: DEPLOY_HAZELCAST|bool
    - role: createNamespace
      when: PREPARE_NAMESPACE|bool
    - role: createDatabase
      when: PREPARE_NAMESPACE|bool
    - role: updateDb
      when: UPDATE_DB|bool
    - role: deployApp
      when: DEPLOY_APP|bool
    - role: setTelegramCommands
    - role: setupWebhook
      when:
        - DEPLOY_APP|bool
        - springProfiles == "webhook"